### ISSUE TITLE
Correct use of not() expresssion

### ISSUE THREAD

**Issue by benr77** [phparkitect/arkitect#162]
|    Q            |   A
|---------------- | ------
| Library version | 0.1.15
| PHP version     | 8.0.8

Thanks for a great tool. I'm exploring setup for my project and have run in to the following issue:

In my `App\UI\Form` namespace, I have two types of classes - form types and form data - e.g. `FooType` and `FooData`. The type classes extend from Symfony's `AbstractType`, whereas the data classes do not extend or implement anything, so I'm trying to use `Not()` to invert the selection for the data classes.

```php
    $formTypeClassNames = Rule::allClasses()
        ->that(new ResideInOneOfTheseNamespaces('App\UI\Form'))
        ->andThat(new Extend(AbstractType::class))
        ->should(new HaveNameMatching('*Type'))
        ->because('we want uniform form type naming');

    $formDataClassNames = Rule::allClasses()
        ->that(new ResideInOneOfTheseNamespaces('App\UI\Form'))
        ->andThat(new Not(new Extend(AbstractType::class)))
        ->should(new HaveNameMatching('*Data'))
        ->because('we want uniform form data class naming');
```

However, this second rule appears to find no classes to work with. Am I querying correctly with the `Not()` expression?

Thank you

**Comment by MatusMak** [comment]
Hello, I'm looking for an open-source project to contribute and I found this one. I like the idea and I see myself using it in my projects in the future, so I would like to offer a help. Are you open to outside contributions?

**Comment by AlessandroMinoccheri** [comment]
Thanks @benr77 for the issue we can try to replicate the problem and create a fix for it.

@MatusMak if you want to contribute you can do it, you can suggest improvements and try to fix bugs like this one, you are welcome.

**Comment by micheleorselli** [comment]
I am just checking the code. As of now the class `Not` is a way do just manipulate the error messages but does not actual perform a logical not on the expression. Since every rule implements a method with the following signature 

`public function evaluate(ClassDescription $theClass, Violations $violations): void`

There is not an easy way to say "take the result of the evaluation of this rule and negate it"

The most straightforward way to implement achieve what you need would it be to create another rule, like `NotExtend`, which operates like `Extends` but negates the result

@benr77 @AlessandroMinoccheri @fain182 what do you think?

**Comment by AlessandroMinoccheri** [comment]
I like the solution to create another rule `NotExtend`.
In my opinion, we can improve the documentation to specify the real means of `Not` because it could be misunderstood.

**Comment by AlessandroMinoccheri** [comment]
@benr77 we have released a new version: `0.2.0` with new classes like `NotExtend` and we removed the `Not` class.
I am closing this issue at the moment, feel free to open new issues if you have new improvements

**Comment by benr77** [comment]
Thank you. I have tested `NotHaveNameMatching` and that is working fine.

I still have issues with `Implement` / `NotImplement` and `Extend` / `NotExtend` which I'll open a new issue for.
